### ISSUE TITLE
It slows down SillyTavern greatly with certain conversations

### ISSUE THREAD

**Issue by Metalhead33** [LenAnderson/SillyTavern-Codex#1]
When I have this extension enabled, loading up certain conversations makes SillyTavern essentially freeze up on the client-side, rendering the whole page within the browser unresponsive.

I am using the following character:

https://chub.ai/characters/LizakJaye/yukari-yakumo

And the following lorebook:

https://chub.ai/lorebooks/hebelover/Touhou-AkyuuKnowledge

SillyTavern is the most recent release version (1.11.2) as of 2024 February 4. I reproduced this issue both on Firefox and Google Chrome, on both desktop Linux and Android.

**Comment by LenAnderson** [comment]
There was an issue with secondary keys in WI entries. Please confirm that the issue is resolved now.
If not resolved, please try to provide an example message or chat history and steps that reliably trigger the issue.

**Comment by Metalhead33** [comment]
Perfect. It works perfectly now, no more freezes.
